// <auto-generated />
using CalculationAppNew;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CalculationAppNew.Migrations
{
    [DbContext(typeof(Model.DBCreationBase))]
    [Migration("20220602110833_V1.0.1")]
    partial class V101
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("CalculationAppNew.Model+CalculationHistory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("DailyExpense")
                        .HasColumnType("REAL");

                    b.Property<double>("FireExtinguisher")
                        .HasColumnType("REAL");

                    b.Property<double>("Grow")
                        .HasColumnType("REAL");

                    b.Property<string>("Mojo")
                        .HasColumnType("TEXT");

                    b.Property<double>("Smile")
                        .HasColumnType("REAL");

                    b.Property<double>("Splurge")
                        .HasColumnType("REAL");

                    b.Property<string>("WhenAdded")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("CalculationHistories");
                });

            modelBuilder.Entity("CalculationAppNew.Model+Expense", b =>
                {
                    b.Property<int>("ExpenseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExpenseAmount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExpenseName")
                        .HasColumnType("TEXT");

                    b.HasKey("ExpenseID");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("CalculationAppNew.Model+Income", b =>
                {
                    b.Property<int>("IncomeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IncomeAmount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IncomeName")
                        .HasColumnType("TEXT");

                    b.HasKey("IncomeID");

                    b.ToTable("Incomes");
                });
#pragma warning restore 612, 618
        }
    }
}
