// <auto-generated />
using CalculationAppNew;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CalculationAppNew.Migrations
{
    [DbContext(typeof(Model.DBCreationBase))]
    [Migration("20220309053603_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.2");

            modelBuilder.Entity("CalculationAppNew.Model+Expense", b =>
                {
                    b.Property<int>("ExpenseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExpenseAmount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExpenseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ExpenseID");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("CalculationAppNew.Model+Income", b =>
                {
                    b.Property<int>("IncomeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IncomeAmount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IncomeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IncomeID");

                    b.ToTable("Incomes");
                });
#pragma warning restore 612, 618
        }
    }
}
